### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Requests' not found in Client.php

### ISSUE THREAD

**Issue by rohitkatiyar1984** [postalserver/postal-php#10]
tried out the PHP library on Localhost Mac with Xampp ..
Installed Composer successfully..
Installed Postal dependencies..
Referenced the source

But I get this error : Fatal error: Uncaught Error: Class 'Requests' not found in /Applications/XAMPP/xamppfiles/htdocs/........../postal-php-master/src/Client.php:27

**Comment by willpower232** [comment]
rmccue/requests is no longer used so this is irrelevant
