### ISSUE TITLE
cURL error 60: SSL certificate problem: self signed certificate

### ISSUE THREAD

**Issue by ederson-cinnamon** [postalserver/postal-php#11]
Hi good day,

when trying to use the api im getting this error.

can I use this package even if testing on localhost?

`\rmccue\requests\library\Requests\Transport\cacert.pem` do I still need to update this file?

I downloaded a cacert.pem file here. https://curl.haxx.se/docs/caextract.htm and updated the `\rmccue\requests\library\Requests\Transport\cacert.pem` but l still im getting the `cURL error 60: SSL certificate problem: self signed certificate`

Thank you.

**Comment by willpower232** [comment]
rmccue/requests is no longer used so this is irrelevant
