### ISSUE TITLE
Does this works with PHP 7,8?

### ISSUE THREAD

**Issue by uhlhosting** [postalserver/postal-php#14]

**Comment by willpower232** [comment]
Thankfully there have been no major deprecations in more recent PHP versions so this library continues to function.

**Comment by xpetter** [comment]
I get some deprecations in PHP 8.1 on rmccue/requests
it is locked (Lock rmccue/requests at v1 to avoid installing v2 which has changed namespaces for PSR reasons.)
But I think they have fixed the deprecations in v2?

**Comment by willpower232** [comment]
The problem with changing to rmccue/requests V2 is that we would have to change all the namespaces used in this project.

We have been preparing a V2 of this library which uses the much more common guzzle dependency instead and hope to release that soon.

**Comment by willpower232** [comment]
v2 was released in July 23 so PHP support is no longer a problem
