### ISSUE TITLE
 'cURL error 60: Peer's Certificate issuer is not recognized.' 

### ISSUE THREAD

**Issue by robp2175** [postalserver/postal-php#9]
PHP Fatal error:  Uncaught exception 'Requests_Exception' with message 'cURL error 60: Peer's Certificate issuer is not recognized.' 

I am getting this error trying to use the API. I have our own certificate installed on the postal server that is working without issue.

**Comment by robp2175** [comment]
Sorry, solved my own problem. Added this to line 392 of vendor/rmccue/requests/library/Requests/Transport/cURL.php

I know the certificate is good, so safe to just ignore.

                        ```
curl_setopt($this->handle, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($this->handle, CURLOPT_SSL_VERIFYPEER, 0);
```

**Comment by SiebeVE** [comment]
I've got the same issue.
I've tracked it down to the package: rmccue/requests
There a cacert.pem is included (https://github.com/rmccue/Requests/blob/master/library/Requests/Transport/cacert.pem) that is used by the curl call.
When providing your own cacert.pem, the error goes away:
```
Requests::set_certificate_path($pathToCaCert);
```

**Comment by ederson-cinnamon** [comment]
@SiebeVE 

Good day,

May I know where did you exactly put `Requests::set_certificate_path($pathToCaCert);` ?

Thank you.

**Comment by SiebeVE** [comment]
In my case it was in a Laravel application and put it in AppServiceProvider in the boot method.
But you can do it in any php project in a place before your first call is initiated, and that is loaded each time your application is started.

**Comment by willpower232** [comment]
rmccue/requests is no longer used so this topic is irrelevant
